// Repositories
export const GAME_REPOSITORY = "GAME_REPOSITORY";
export const PAWN_REPOSITORY = "PAWN_REPOSITORY";
export const PLAYER_REPOSITORY = "PLAYER_REPOSITORY";
export const ROUND_REPOSITORY = "ROUND_REPOSITORY";
export const SOCKET_REPOSITORY = "SOCKET_REPOSITORY";

// Providers
export const BROKER_PROVIDER = "BROKER_PROVIDER";
export const WEBHOOK_PROVIDER = "WEBHOOK_PROVIDER";
