// https://www.typescriptlang.org/play#code/PTAEFpK6dv4YpSCwAoEoCKBXApgM4AuAlgPYB2oAjOngB4AOZATkaEQJ6N6gDKOAEZ88RaqAC8oAETVpoAD4yATPKXSAzGpkAWbdICs0gNx0mrdlx78hIosskyAbPoDs+gBz6AnPuoAGEzNmNg5uXjtHAWFRcSVou2VTNHQAY0piUAA3AEMAG3wCAC5QAEEWFhzOAB47AD5HAG1pVQAaGS0AXWT0ikzcgrwSyKlpF2S0jLI8vAA6PLIAcwAKAcLZkgpUgoATQlX8-ABKI+TMAHUAC05QHbJQAElQS5ys3iJL3kYWPCzyHAIoDwFVYAH50OhMAAVT6gAC2okuZB2oAIJEWFByRBwP1AJEBH3xRQhGDAmyIwIAZjlUrxypUalCGgBvSFgUB4ra7fYEPA5FipS4AURmCIoRBKUPalJYZDhDwoe3ooJKFBwcMEwKOJUEZGmfIoZzAAF8SRdLiRBfCDQR2ptQJwyDjQKkcrziSlSZyKSxqbSyhUqqBWV6OZttjg9gRlrz+YKRXgxRKbDExNLZfLFQwVaA1RqtTq9TMcoa2aBTZ7MAB5FjtAAGazwdZdJdAmtAZEpYWsCVi7UEOHYrqo+QI93bne7EVsomUZah9wA7qwANbtD68BEfZGo9GY7G4ghInB5FGaj1l8lUml0wOMlllsNcyM8vkC4WivDiko4CgrihkIuFDpnKCpKjmeaaiw2ptkWBpGuWZpgDWoD8gyU6osep5tkMLoZOwjbFAGDK1KIDRSM0bQdNI3RIRAyAMYxTHMbAZa4IQpCUKAc6egwISWOEoAAMJurwow7HIigyDsqhSdIOxaHJOx6D0+GwfQhAlPSVTVCJvLkaAzQSdI7TyVR8ldMYoCYE8y4niieQkCuvCtsCsosKiVSbIstw6HigJwviaIUIsdEABKAS2VBPFYvC6hpBL3C8byoVQbmsHiXZ8lajb+bmZDsN8hBfuw9obqhd7gpWYAPF2jo4KAi4lpY9yxepmkkm1QmUEQlS5CwJDNdUTKOFCQL0BSiqAr+-6AVQoKgMsAD6kpHJIDRZGQJAoqqvzAskbUKpSwLdeKfX8oN4rDQZjRQp042TTsgKNMtJSbMdHkPGtEgbVtOz3QtTy7W8LATGgbUAAqWiuVYUHg12OEdJ09edA1DegHJIywp29a8F1DTjqOXUQuko3jaNXUydR1OgdRg21ACqFDkBQC5QjgjAzAjUhQ6kMNwwjDCPYC73AqADMY6AC1CvQEZ7MN7QMw0Qtfk9uZ7Swkscgtt2dFroAlI0szG0zLNsxzXMy3L8NSuL1OK3raAcsD+0kr0mTxYQ1AlKblDm5z8N6XgN3yXIpkySZ0mWXRABCg6PM8-I7HkNw-OkcJwiWKIkEQ7QMLSjClXVTqJylAEdhuHmClttJlrVDol-yvB7NsF0hRwsL9YNggzO09VRS6PxYu8sJtTKcod7wuXLOVZCMMwaIUo1VTam7amewQDgUaHkdmbvCn73o91unhfREAdglB1vi2xZOG-KEcjSQcCtFoEAA

type Contravariant<T> = T extends unknown ? (_: T) => void : never;
type InferContravariant<T> = [T] extends [(_: infer I) => void] ? I : never;

type PickOne<T> = InferContravariant<
  InferContravariant<Contravariant<Contravariant<T>>>
>;

export type UnionToTuple<T> = PickOne<T> extends infer U
  ? Exclude<T, U> extends never
    ? [T]
    : [...UnionToTuple<Exclude<T, U>>, U]
  : never;
